<?php

/* * ********************************************************************
 * Customization Services by ModulesGarden.com
 * Copyright (c) ModulesGarden, INBS Group Brand, All Rights Reserved 
 * (2014-07-04, 13:59:14)
 * 
 *
 *  CREATED BY MODULESGARDEN       ->        http://modulesgarden.com
 *  CONTACT                        ->       contact@modulesgarden.com
 *
 *
 *
 *
 * This software is furnished under a license and may be used and copied
 * only  in  accordance  with  the  terms  of such  license and with the
 * inclusion of the above copyright notice.  This software  or any other
 * copies thereof may not be provided or otherwise made available to any
 * other person.  No title to and  ownership of the  software is  hereby
 * transferred.
 *
 *
 * ******************************************************************** */

/**
 * @author Grzegorz Draganik <grzegorz@modulesgarden.com>
 */
?>

<p class="bug-report">
    <?php echo $this->__('Interface Locale: %s', $this->getLanguageSelect()) ?>
</p>
<p class="legality">
    <img src="<?php echo $this->getSkinUrl('images/varien_logo.gif') ?>" class="v-middle" alt="" />&nbsp;&nbsp;
    <?php echo $this->__('Magento&trade; is a trademark of Magento Inc.<br/>Copyright &copy; %s Magento Inc.', date('Y')) ?>
</p>
<div style="text-align:center;"><?php echo $this->__('Magento ver. %s', Mage::getVersion()) ?></div>
<script type="text/javascript">
    $('footer_bug_tracking').target = 'Varien_External';
    $('footer_connect').target = 'Varien_External';
    function setInterfaceLanguage(evt){
        var elem = Event.element(evt);
        if(elem){
            setLocation('<?php echo $this->getChangeLocaleUrl() ?>locale/'+elem.value+'/<?php echo $this->getRefererParamName() ?>/<?php echo $this->getUrlForReferer() ?>');
        }
    }
    Event.observe('interface_locale', 'change', setInterfaceLanguage)
</script>
