<?php
/**
 * Philwinkle_AppliedPatches Extension
 *
 * NOTICE OF LICENSE
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 *
 * @category  Magento
 * @package   Philwinkle_AppliedPatches
 * @author    Phillip Jackson <philwinkle@gmail.com>
 * @copyright Copyright (c) 2015 Philwinkle LLC
 */
?>
<?php
/**
 * AppliedPatches template - displays the patch versions in Magento admin
 *
 * @see Mage_Core_Block_Template
 */
?>
<script>
	document.observe('dom:loaded',function(){
		var patchesText = $('philwinkle-applied-patches').text;
		var footer = $$('.footer')[0];

		footer.insert({bottom: patchesText});
	});
</script>
<script type="text/template" id="philwinkle-applied-patches">
<?php echo $this->helper('appliedpatches')->getPatches();?>
</script>
